-- -------------------------------------------------------------
-- TablePlus 5.4.2(506)
--
-- https://tableplus.com/
--
-- Database: postgres
-- Generation Time: 2023-10-06 16:38:05.8390
-- -------------------------------------------------------------
-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.
-- Table Definition
CREATE TABLE "public"."general_overview"(
	id int GENERATED BY DEFAULT AS IDENTITY,
	"thema" text,
	"typ" text,
	"datensatz_titel" text,
	"beschreibung" text,
	"raeumlicher_bezug" text,
	"verantwortlichkeit_bezirksebene" text,
	"ansprechperson_bezirksebene" text,
	"verantwortlichkeit_landesebene" text,
	"ansprechperson_landesebene" text,
	"datenhoheit_bei" text,
	"it_fachverfahren" text,
	"dateiformat" text,
	"datenqualitaet" text,
	PRIMARY KEY ("id")
);

