name: Vite Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x,20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            add-in/et

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          cd add-in/et
          npm ci
          npm run build
